services:
  # =========================
  # SQL Server
  # =========================
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend

  # =========================
  # SQL Init (Database + Table)
  # =========================
  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlserver-init
    depends_on:
      - sqlserver
    networks:
      - backend
    entrypoint: >
      /bin/bash -c "
      echo '⏳ Aguardando SQL Server...' &&
      sleep 25 &&
      /opt/mssql-tools/bin/sqlcmd
        -S sqlserver
        -U sa
        -P 'YourStrong!Passw0rd'
        -Q \"
        IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'BancoKrt')
        BEGIN
            CREATE DATABASE BancoKrt;
        END;
        USE BancoKrt;
        IF NOT EXISTS (
            SELECT * FROM sysobjects WHERE name='Accounts' AND xtype='U'
        )
        BEGIN
            CREATE TABLE Accounts (
                Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
                HolderName NVARCHAR(200) NOT NULL,
                Cpf CHAR(11) NOT NULL,
                Status INT NOT NULL
            );
        END;
        \"
      "
    restart: "no"

  # =========================
  # Redis
  # =========================
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  # =========================
  # Zookeeper
  # =========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend

  # =========================
  # Kafka
  # =========================
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

  # =========================
  # Kafka Topic Init
  # =========================
  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-init
    depends_on:
      - kafka
    networks:
      - backend
    entrypoint: >
      /bin/bash -c "
      echo '⏳ Aguardando Kafka...' &&
      sleep 20 &&
      kafka-topics
        --bootstrap-server kafka:9092
        --create
        --if-not-exists
        --topic accounts-events
        --partitions 1
        --replication-factor 1 &&
      echo '✅ Tópico accounts-events criado'
      "
    restart: "no"

volumes:
  sqlserver_data:

networks:
  backend:
    driver: bridge